### ISSUE TITLE
Feature request, add header to different files.

### ISSUE THREAD

**Issue by 51M0Ng** [ngoanh2n/csv-comparator#2]
Hi developer.

I found out the different output file doesn't contain header files. But for my case, I need a header inside the output files as well. Would you please check is missing features or are incorrect operations?

**Comment by ngoanh2n** [comment]
Hi @51M0Ng 
Thank you for your request.
It's going to solve it.

**Comment by ngoanh2n** [comment]
https://github.com/ngoanh2n/csv-comparator/releases/tag/1.2.0
